services:
  # backend:
  #   container_name: funancebackend
  #   restart: always
  #   build: ./
  #   ports:
  #     - 3000:3000
  #   external_links:
  #     - funancedb
  mongo:
    container_name: funancedb
    image: mongo
    restart: always
    env_file:
      - mongo.env
    environment:
      TZ: America/Sao_Paulo
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - mongo-exp.env
